[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "pnpm dev"
  port = 3000
  targetPort = 3000
  framework = "#custom"
  autoLaunch = false
